[package]
name = "spaced"
version = "0.0.0"
description = "Desktop app for Spaced"
repository = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[build-dependencies]
tauri-build = { version = "1", features = [] }
tonic-build = "0.10"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tauri = { version = "1", features = [] }
tokio = { version = "1", features = ["full"] }
tonic = "0.10"
prost = "0.12"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
