[workspace]
members = [
  "tauri",
  "server",
]
resolver = "2"

[workspace.package]
authors = ["Tauri Programme within The Commons Conservancy"]
homepage = "https://tauri.app/"
repository = "https://github.com/tauri-apps/tauri"
categories = ["gui", "web-programming", "http-server"]
license = "Apache-2.0 OR MIT"
edition = "2021"
rust-version = "1.65"

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

# [package]
# name = "spaced"
# version = "0.0.0"
# description = "A Tauri App"
# authors = ["you"]
# license = ""
# repository = ""
# edition = "2021"

# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [build-dependencies]
# tauri-build = { version = "1.4", features = [] }

# [dependencies]
# tauri = { version = "1.4", features = [] }
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
# tokio = { version = "1.32.0", features = ["full"] }
# anyhow = "1.0.75"

# [features]
# # this feature is used for production builds or when `devPath` points to the filesystem
# # DO NOT REMOVE!!
# custom-protocol = ["tauri/custom-protocol"]
