version: '3.8'

services:
  # A persistent database for local development.
  postgres-dev:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: spaced
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
