[package]
name = "spaced-server"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
serde = "1.0.188"
tokio = "1.32.0"
