name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  RUSTFLAGS: '-Dwarnings'
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  app_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npx tsc

  format_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run fmt

  lint_rust:
    uses: ./.github/workflows/clippy.yaml

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: docker/bake-action@v4
