CREATE TABLE IF NOT EXISTS item
(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  color VARCHAR(7),
  -- w INTEGER NOT NULL,
  -- h INTEGER NOT NULL,
  -- content_type VARCHAR(10) NOT NULL
  -- content_length INTEGER NOT NULL
  data TEXT NOT NULL
);
